name: Kontoauszuege
main: de.ersterstreber.kontauszuege.Kontoauszug
version: 1.8
author: ersterstreber
softdepends: [CraftConomy, SimpleRegionMarket, ChestShop]
commands:
     konto:
          description: Zeigt deine Kontoauszuege an.
          aliases: [k]
     gkonto:
          description: Der GKonto-Hauptkommand.
          aliases: [gk]
     statement:
          description: Zeigt eine Zusammenfassung der Einnahmen und Ausgaben.
          aliases: [s]