name: Kontoauszug
main: de.ersterstreber.kontauszuege.Kontoauszug
version: 1.5
author: ersterstreber
softdepends: [CraftConomy, SimpleRegionMarket, ChestShop]
commands:
     konto:
          description: Zeigt deine Kontoauszuege.
          aliases: [k]
     gkonto:
          description: Der GKonto-Hauptkommand.
          aliases: [gk]
     statement:
          description: Zeigt eine Zusammenfassung der Einnahmen und Ausgaben
          aliases: [s]